import random

def get_random_question():
    questions = [
        "What am I looking at?",
        "Can you tell me what this is?",
        "What does this show?",
        "What exactly is this?",
        "Can you identify this?",
        "What do you see here?",
        "What’s in this image?",
        "What is depicted here?",
        "What’s this supposed to be?",
        "Do you know what this is?",
        "What is shown here?",
        "What kind of thing is this?",
        "Can you explain this?",
        "What’s the subject of this image?",
        "What’s going on in this picture?",
        "What is represented here?",
        "Can you describe this?",
        "What object is this?",
        "What’s this all about?",
        "Can you name this?",
        "What kind of object is this?",
        "What is happening in this image?",
        "What is visible here?",
        "What is this thing?",
        "What is this called?",
        "What’s in front of me?",
        "What’s in this photo?",
        "What’s here?",
        "What are you looking at?",
        "What is being displayed?",
        "Can you recognize this?",
        "What is shown in this image?",
        "Can you tell what this is?",
        "What is present in this picture?",
        "What’s pictured here?",
        "What can be seen here?",
        "What does this represent?",
        "What are we seeing?",
        "What is portrayed here?",
        "What’s captured in this image?",
        "What’s illustrated here?",
        "What’s this thing?",
        "What’s in view?",
        "What is this image showing?",
        "What’s the content of this picture?",
        "What’s visible in this scene?",
        "Can you describe what’s here?",
        "What is this an image of?",
        "What could this be?",
        "What does this photo show?",
        "What is this item?",
        "What do you think this is?",
        "What’s in this view?",
        "What is seen in this image?",
        "What’s the focus of this picture?",
        "What’s going on here?",
        "What is this photo depicting?",
        "What object is shown here?",
        "What is presented here?",
        "What is captured in this photo?",
        "What is the subject of this image?",
        "What can you see here?",
        "What’s drawn here?",
        "What might this be?",
        "What do you think is in this image?",
        "What’s displayed here?",
        "What can be recognized here?",
        "What’s illustrated in this photo?",
        "What is this photo of?",
        "What is being shown?",
        "What is in this picture?",
        "What object does this represent?",
        "What is featured in this image?",
        "What is this picture about?",
        "What can you identify here?",
        "What can you make out from this?",
        "What’s this thing called?",
        "What’s the object shown here?",
        "What does this photo represent?",
        "What do you think this object is?",
        "What’s in this scene?",
        "What’s portrayed in this picture?",
        "What might be visible here?",
        "What’s here in this image?",
        "What can you tell from this image?",
        "What is this photo showing?",
        "What’s the focus of this scene?",
        "What does this picture capture?",
        "What is depicted in this photo?",
        "What’s the subject in this frame?",
        "What’s in this snapshot?",
        "What is observable here?",
        "What is this frame about?"
    ]
    return random.choice(questions)


